apiVersion: apps/v1
kind: Deployment
metadata:
  name: session17-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session17-python
  template:
    metadata:
      labels:
        app: session17-python
    spec:
      containers:
        - name: session17-python
          image: ghcr.io/__IMAGE_OWNER__/session17-python:__IMAGE_TAG__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
