apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskboard.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: taskboard-backend
  template:
    metadata:
      labels:
        app: taskboard-backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "taskboard.fullname" . }}-config
          env:
            - name: DB_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.postgres.database | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: password
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 15
          resources:
{{ toYaml .Values.resources | indent 12 }}
